var width=window.innerWidth;
var canvas_width=$("#playing_area").css("width");
var canvas_height=$("#playing_area").css("height");
var length=canvas_width.length;
var canvas = document.getElementById("playing_area");
var ctx=canvas.getContext("2d");
canvas_width=parseInt(canvas_width.substring(0,length-2));
var height=canvas_height.length;
canvas_height=parseInt(canvas_height.substring(0,length-2));
var front_width=(width-canvas_width)/2;
var factor=0.2;
var your_score_height=canvas_height*factor;
var control_height=canvas_height*(1-2*factor);
var arrow_width=50;
var arrow_height=50;
var between_arrow_margin=25;
var top_arrow_margin_top=between_arrow_margin;
var top_arrow_margin_left=(front_width-arrow_width)/2;
var left_arrow_margin_left=(front_width-arrow_width)/2-between_arrow_margin-(arrow_width);
var left_arrow_margin_top=between_arrow_margin;
var right_arrow_margin_left=2*between_arrow_margin+arrow_width;
var right_arrow_margin_top=left_arrow_margin_top;
var bottom_arrow_margin_left=top_arrow_margin_left;
var bottom_arrow_margin_top=2*between_arrow_margin+arrow_height;
var border=15;
ctx.fillStyle="grey";
ctx.fillRect(0,0,canvas_width,border);
ctx.fillRect(0,border,border,canvas_height);
ctx.fillRect(border,canvas_height-border,canvas_width,canvas_height);
ctx.fillRect(canvas_width-border,border,canvas_width,canvas_height-border);
width+="px";
canvas_width+="px";
canvas_height+="px";
front_width+="px";
your_score_height+="px";
control_height+="px";
arrow_width+="px";
arrow_height+="px";
between_arrow_margin+="px";
top_arrow_margin_top+="px";
top_arrow_margin_left+="px";
left_arrow_margin_left+="px";
left_arrow_margin_top+="px";
right_arrow_margin_top+="px";
right_arrow_margin_left+="px";
bottom_arrow_margin_top+="px";
bottom_arrow_margin_left+="px";
$("#start").css({ "width" : width , "height" : canvas_height });
$("#front").css({ "width" : front_width , "height" : canvas_height , "float" : "left" });
$("#middle").css({ "width" : canvas_width , "height" : canvas_height , "float" : "left"});
$("#last").css({ "width" : front_width , "height" : canvas_height , "float" : "left"});
$("#your_score_display").css({ "width" : front_width , "height" : your_score_height , "background-color" : "lightgreen"});
$("#high_score_display").css({ "width" : front_width , "height" : your_score_height , "background-color" : "powderblue"});
$("#controls").css({ "width" : front_width , "height" : control_height , "background-color" : "white"});
$("#controls_text").css({ "margin-top" : "0px" , "font-size" : "25px" , "text-align" : "center" });
$("#top_arrow").css({ "width" : arrow_width , "height" : arrow_height , "margin-top" : top_arrow_margin_top , "margin-left" : top_arrow_margin_left });
$("#top_arrow_img").css({ "width" : arrow_width , "height" : arrow_height ,"margin" : "0px" });
$("#top_arrow_btn").css({ "padding" : "0px" });
$("#left_arrow").css({ "width" : arrow_width , "height" : arrow_height , "float" : "left" ,"margin-top" : left_arrow_margin_top , "margin-left" : left_arrow_margin_left });
$("#left_arrow_img").css({ "width" : arrow_width , "height" : arrow_height ,"margin" : "0px" });
$("#left_arrow_btn").css({ "padding" : "0px" });
$("#right_arrow").css({ "width" : arrow_width , "height" : arrow_height  ,  "float" : "left","margin-top" : right_arrow_margin_top , "margin-left" : right_arrow_margin_left});
$("#right_arrow_img").css({ "width" : arrow_width , "height" : arrow_height ,"margin" : "0px" });
$("#right_arrow_btn").css({ "padding" : "0px" });
$("#bottom_arrow").css({ "width" : arrow_width , "height" : arrow_height , "margin-top" : bottom_arrow_margin_top , "margin-left" : bottom_arrow_margin_left});
$("#bottom_arrow_img").css({ "width" : arrow_width , "height" : arrow_height ,"margin" : "0px" });
$("#bottom_arrow_btn").css({ "padding" : "0px" });
$("#your_score_text").css({ "margin-top" : "0px" ,"margin-bottom" : "0px" , "text-align" : "center" , "font-size" : "25px" , "color" : "white" });
$("#your_score_score").css({ "margin-top" : "15px" ,"text-align" : "center" , "font-size" : "40px" , "color" : "white" });
$("#high_score_text").css({ "margin-top" : "0px" ,"margin-bottom" : "0px" , "text-align" : "center" , "font-size" : "25px" , "color" : "white" });
$("#high_score_score").css({ "margin-top" : "15px" ,"text-align" : "center" , "font-size" : "40px" , "color" : "white" });
$("#blank_area").css({ "width" : front_width , "height" : your_score_height });